services:
  db:
    image: postgres
    container_name: drf_postgres
    environment:
      POSTGRES_USER: drf_postgres_user
      POSTGRES_PASSWORD: drf_postgres_password
      POSTGRES_DB: drf_postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: