# Generated by Django 5.2.3 on 2025-06-30 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementationDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('LWC', 'Lightning Web Component'), ('APEX', 'Apex Class/Trigger'), ('FLOW', 'Flow'), ('CONFIG', 'Configuración'), ('PERMISSION', 'Permission Set'), ('METADATA', 'Metadata'), ('OTHER', 'Otro')], max_length=50)),
                ('content', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='tasks.task')),
            ],
        ),
    ]
