# Generated by Django 5.2.3 on 2025-06-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('client', models.CharField(max_length=255)),
                ('project', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('APEX', 'Apex'), ('LWC', 'Lightning Web Component'), ('FLOW', 'Flow'), ('CONFIG', 'Declarativo'), ('INTEGRATION', 'Integración'), ('METADATA', 'Metadata'), ('OTHER', 'Otro')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_PROGRESS', 'En progreso'), ('REVIEW', 'En revisión'), ('BLOCKED', 'Bloqueada'), ('COMPLETED', 'Completada')], default='DRAFT', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
